import {createTheme} from '@mui/material/styles';

const headingFont = "'Space Grotesk', 'Inter', sans-serif";
const bodyFont = "'Inter', 'Lato', sans-serif";

export const theme = createTheme({
    colors:{
        main:'#0e1117',
        surface:'#1a1f2e',
        surface2:'#252b3a',
        light:'#2d3650',
        gray:'#b0bcd8',
        grayLight:'#f0f4ff',
        green:'#4ade80',
        naval:'#40739e',
        cyan:'#00a8ff',
        psBlue:'#0067dd',
        secondary:'#8338ec',
        border:'rgba(255,255,255,0.08)',
    },
    fonts:{
        main:bodyFont,
        heading:headingFont,
    },
    fontW:{
        thin:'300',
        normal:'400',
        bold:'600',
        black:'700'
    },
    palette:{
        mode:'dark',
        primary:{
            main:'#0067dd',
            light:'#3399ff',
            dark:'#004faa',
        },
        secondary:{
            main:'#8338ec',
        },
        background:{
            default:'#0e1117',
            paper:'#1a1f2e',
        },
        text:{
            primary:'#eef2ff',
            secondary:'#a8b8d8',
        },
        success:{
            main:'#4ade80',
        },
        error:{
            main:'#ef4444',
        },
        warning:{
            main:'#f59e0b',
        },
    },
    shape:{
        borderRadius:12,
    },
    typography:{
        fontFamily:bodyFont,
        h1:{
            color:'#eef2ff',
            fontFamily:headingFont,
            fontWeight:700,
            letterSpacing:'-0.02em',
        },
        h2:{
            color:'#eef2ff',
            fontFamily:headingFont,
            fontWeight:700,
            letterSpacing:'-0.015em',
        },
        h3:{
            color:'#eef2ff',
            fontFamily:headingFont,
            fontWeight:700,
            fontSize:'2rem',
            letterSpacing:'-0.01em',
        },
        h4:{
            color:'#eef2ff',
            fontFamily:headingFont,
            fontWeight:600,
        },
        h5:{
            color:'#c8d4f0',
            fontFamily:headingFont,
            fontWeight:500,
            fontSize:'1.15rem',
        },
        h6:{
            color:'#c8d4f0',
            fontFamily:headingFont,
            fontWeight:500,
        },
        body1:{
            color:'#d0daf0',
            fontFamily:bodyFont,
        },
        body2:{
            color:'#a8b8d8',
            fontFamily:bodyFont,
        },
        mainProductTitle:{
            color:'#eef2ff',
            fontFamily:headingFont,
            fontWeight:700,
            textAlign:'center',
            fontSize:'2.8rem',
            letterSpacing:'-0.02em',
        },
        productTitle:{
            color:'white',
            fontFamily:headingFont,
            fontWeight:600,
            textAlign:'center',
        },
        rowLight:{
            fontFamily:bodyFont,
            fontWeight:400,
            fontSize:'1rem',
            color:'#b8c8e8',
            lineHeight:1.8,
        },
        rowNormal:{
            fontFamily:bodyFont,
            fontWeight:400,
            fontSize:'1rem',
            color:'#d0daf0',
        },
        rowBold:{
            fontFamily:bodyFont,
            fontWeight:600,
            fontSize:'1rem',
            color:'#eef2ff',
        },
        rowBlack:{
            fontFamily:headingFont,
            fontWeight:700,
            fontSize:'1rem',
            color:'#eef2ff',
        },
    },
    TableCell:{
        headCell:{
            fontFamily:headingFont,
        }
    },
    components:{
        MuiOutlinedInput:{
            styleOverrides:{
                root:{
                    '& .MuiOutlinedInput-notchedOutline':{
                        borderColor:'rgba(255,255,255,0.2)',
                    },
                    '&:hover .MuiOutlinedInput-notchedOutline':{
                        borderColor:'rgba(255,255,255,0.4)',
                    },
                    '&.Mui-focused .MuiOutlinedInput-notchedOutline':{
                        borderColor:'#0067dd',
                    },
                    '& .MuiInputBase-input':{
                        color:'#eef2ff',
                    },
                },
            },
        },
        MuiInputLabel:{
            styleOverrides:{
                root:{
                    color:'#8090b8',
                    fontFamily:bodyFont,
                    '&.Mui-focused':{
                        color:'#3399ff',
                    },
                },
            },
        },
        MuiFormControlLabel:{
            styleOverrides:{
                label:{
                    color:'#a8b8d8',
                    fontSize:'0.9rem',
                    fontFamily:bodyFont,
                },
            },
        },
        MuiTableCell:{
            styleOverrides:{
                root:{
                    borderBottom:'1px solid rgba(255,255,255,0.06)',
                    fontFamily:bodyFont,
                    color:'#c8d8f0',
                },
            },
        },
        MuiDivider:{
            styleOverrides:{
                root:{
                    borderColor:'rgba(255,255,255,0.08)',
                },
            },
        },
        MuiListItemText:{
            styleOverrides:{
                primary:{
                    color:'#c8d8f0',
                    fontFamily:bodyFont,
                },
            },
        },
        MuiMenuItem:{
            styleOverrides:{
                root:{
                    fontFamily:bodyFont,
                    color:'#d0daf0',
                },
            },
        },
        MuiTypography:{
            styleOverrides:{
                root:{
                    letterSpacing:'inherit',
                },
            },
        },
        MuiButton:{
            styleOverrides:{
                root:{
                    fontFamily:headingFont,
                    fontWeight:600,
                    letterSpacing:'0.01em',
                },
            },
        },
        MuiAppBar:{
            styleOverrides:{
                root:{
                    backgroundImage:'none',
                },
            },
        },
    },
})
