import {createTheme} from '@mui/material/styles';

const headingFont = "'Space Grotesk', 'Inter', sans-serif";
const bodyFont = "'Inter', 'Lato', sans-serif";

export const theme = createTheme({
    colors:{
        main:'#f5f7fb',
        surface:'#ffffff',
        surface2:'#f0f4ff',
        light:'#e8f0ff',
        gray:'#6b7a99',
        grayLight:'#0d1b3e',
        green:'#00a86b',
        naval:'#2c3e6a',
        cyan:'#0058cc',
        psBlue:'#003791',
        secondary:'#7b2fff',
        border:'#e2e8f4',
    },
    fonts:{
        main:bodyFont,
        heading:headingFont,
    },
    fontW:{
        thin:'300',
        normal:'400',
        bold:'600',
        black:'700'
    },
    palette:{
        mode:'light',
        primary:{
            main:'#003791',
            light:'#0058cc',
            dark:'#002268',
            contrastText:'#ffffff',
        },
        secondary:{
            main:'#7b2fff',
        },
        background:{
            default:'#f5f7fb',
            paper:'#ffffff',
        },
        text:{
            primary:'#0d1b3e',
            secondary:'#6b7a99',
        },
        success:{
            main:'#00a86b',
        },
        error:{
            main:'#e53935',
        },
        warning:{
            main:'#f59e0b',
        },
    },
    shape:{
        borderRadius:12,
    },
    typography:{
        fontFamily:bodyFont,
        h1:{
            color:'#0d1b3e',
            fontFamily:headingFont,
            fontWeight:700,
            letterSpacing:'-0.02em',
        },
        h2:{
            color:'#0d1b3e',
            fontFamily:headingFont,
            fontWeight:700,
            letterSpacing:'-0.015em',
        },
        h3:{
            color:'#0d1b3e',
            fontFamily:headingFont,
            fontWeight:700,
            fontSize:'2rem',
            letterSpacing:'-0.01em',
        },
        h4:{
            color:'#0d1b3e',
            fontFamily:headingFont,
            fontWeight:600,
        },
        h5:{
            color:'#2c3e6a',
            fontFamily:headingFont,
            fontWeight:500,
            fontSize:'1.15rem',
        },
        h6:{
            color:'#2c3e6a',
            fontFamily:headingFont,
            fontWeight:500,
        },
        body1:{
            color:'#2c3e6a',
            fontFamily:bodyFont,
        },
        body2:{
            color:'#6b7a99',
            fontFamily:bodyFont,
        },
        mainProductTitle:{
            color:'#0d1b3e',
            fontFamily:headingFont,
            fontWeight:700,
            textAlign:'left',
            fontSize:'2.2rem',
            letterSpacing:'-0.02em',
        },
        productTitle:{
            color:'white',
            fontFamily:headingFont,
            fontWeight:600,
            textAlign:'center',
        },
        rowLight:{
            fontFamily:bodyFont,
            fontWeight:400,
            fontSize:'1rem',
            color:'#4a5a7a',
            lineHeight:1.85,
        },
        rowNormal:{
            fontFamily:bodyFont,
            fontWeight:400,
            fontSize:'1rem',
            color:'#2c3e6a',
        },
        rowBold:{
            fontFamily:bodyFont,
            fontWeight:600,
            fontSize:'1rem',
            color:'#0d1b3e',
        },
        rowBlack:{
            fontFamily:headingFont,
            fontWeight:700,
            fontSize:'1rem',
            color:'#0d1b3e',
        },
    },
    TableCell:{
        headCell:{
            fontFamily:headingFont,
        }
    },
    components:{
        MuiOutlinedInput:{
            styleOverrides:{
                root:{
                    backgroundColor:'#ffffff',
                    '& .MuiOutlinedInput-notchedOutline':{
                        borderColor:'#d0d8ea',
                    },
                    '&:hover .MuiOutlinedInput-notchedOutline':{
                        borderColor:'#003791',
                    },
                    '&.Mui-focused .MuiOutlinedInput-notchedOutline':{
                        borderColor:'#003791',
                    },
                    '& .MuiInputBase-input':{
                        color:'#0d1b3e',
                    },
                },
            },
        },
        MuiInputLabel:{
            styleOverrides:{
                root:{
                    color:'#6b7a99',
                    fontFamily:bodyFont,
                    '&.Mui-focused':{
                        color:'#003791',
                    },
                },
            },
        },
        MuiFormControlLabel:{
            styleOverrides:{
                label:{
                    color:'#2c3e6a',
                    fontSize:'0.9rem',
                    fontFamily:bodyFont,
                },
            },
        },
        MuiTableCell:{
            styleOverrides:{
                root:{
                    borderBottom:'1px solid #f0f4f8',
                    fontFamily:bodyFont,
                    color:'#2c3e6a',
                },
            },
        },
        MuiDivider:{
            styleOverrides:{
                root:{
                    borderColor:'#e2e8f4',
                },
            },
        },
        MuiListItemText:{
            styleOverrides:{
                primary:{
                    color:'#0d1b3e',
                    fontFamily:bodyFont,
                },
            },
        },
        MuiMenuItem:{
            styleOverrides:{
                root:{
                    fontFamily:bodyFont,
                    color:'#0d1b3e',
                    '&:hover':{
                        background:'#f0f4ff',
                    },
                },
            },
        },
        MuiButton:{
            styleOverrides:{
                root:{
                    fontFamily:headingFont,
                    fontWeight:600,
                    letterSpacing:'0.01em',
                    textTransform:'none',
                    borderRadius:'10px',
                },
                contained:{
                    boxShadow:'none',
                    '&:hover':{
                        boxShadow:'0 4px 20px rgba(0,55,145,0.25)',
                        transform:'translateY(-1px)',
                    },
                    transition:'all 0.2s ease',
                },
            },
        },
        MuiAppBar:{
            styleOverrides:{
                root:{
                    backgroundImage:'none',
                    backgroundColor:'#ffffff',
                    color:'#0d1b3e',
                    boxShadow:'0 1px 0 #e2e8f4',
                },
            },
        },
        MuiPaper:{
            styleOverrides:{
                root:{
                    backgroundImage:'none',
                },
            },
        },
        MuiDrawer:{
            styleOverrides:{
                paper:{
                    backgroundImage:'none',
                },
            },
        },
        MuiBadge:{
            styleOverrides:{
                badge:{
                    fontFamily:headingFont,
                    fontWeight:700,
                },
            },
        },
        MuiChip:{
            styleOverrides:{
                root:{
                    fontFamily:bodyFont,
                },
            },
        },
    },
})
